export const wsUrl = "wss://simple-chat-api-production.up.railway.app";

export const members = [
  {
    name: "Mark Zuckerberg",
    img: "https://sun9-11.userapi.com/c857632/v857632946/16fee5/Qwk4Z7DvdTA.jpg",
    message:
      "Yes, I need your help with the project, it needs to be done by tomorrow 😫",
    country: "United States",
    city: "California",
    phone: "(123) 456-7890",
    socialMedia: [
      { name: "Instagram", link: "https://www.instagram.com/markzuck/" },
      { name: "LinkedIn", link: "https://www.linkedin.com/in/markzuck/" },
    ],
    activities: ["Biking", "Cooking", "Traveling", "Graphic design"],
    status: "Your status message goes here.",
  },
  {
    name: "Сениор Фронтендер",
    img: "https://pbs.twimg.com/profile_images/958182062342705152/SISZWpyS_400x400.jpg",
    message:
      "Yes, I need your help with the project, it needs to be done by tomorrow 😫",
    country: "Russia",
    city: "Moscow",
    phone: "(987) 654-3210",
    socialMedia: [
      { name: "Instagram", link: "https://www.instagram.com/seniorfrontend/" },
      { name: "LeetCode", link: "https://leetcode.com/seniorfrontend/" },
    ],
    activities: ["Biking", "Cooking", "Traveling", "Graphic design"],
    status:
      "Fly me to the moon 🌙 If you feel like your life is a routine, step back and take a deep breath.",
  },
  {
    name: "John Doe",
    img: "https://image.pngaaa.com/104/3298104-middle.png",
    message: "Hey there, looking forward to working together!",
    country: "United States",
    city: "New York",
    phone: "(555) 123-4567",
    socialMedia: [
      { name: "Twitter", link: "https://twitter.com/johndoe/" },
      { name: "LinkedIn", link: "https://www.linkedin.com/in/johndoe/" },
    ],
    activities: ["Reading", "Hiking", "Photography", "Yoga"],
    status: "Just living my best life! 🌟",
  },
  {
    name: "Michael Wang",
    img: "https://avatars.mds.yandex.net/i?id=506c55d6f16c965a579c407be34dca33_l-4472919-images-thumbs&ref=rim&n=13&w=1125&h=639",
    message: "Hi there, let's make this project awesome!",
    country: "Canada",
    city: "Vancouver",
    phone: "(123) 456-7890",
    socialMedia: [
      { name: "GitHub", link: "https://github.com/michaelwang/" },
      { name: "LinkedIn", link: "https://www.linkedin.com/in/michaelwang/" },
    ],
    activities: ["Hiking", "Photography", "Chess", "Web development"],
    status: "Embracing challenges with a smile! 😄",
  },
  {
    name: "Robert Kim",
    img: "https://yt3.ggpht.com/ytc/AKedOLRN2-40YgV2__fSRp_UkSzY8unH2ekT6z6BT06X5Q=s900-c-k-c0x00ffffff-no-rj",
    message: "Looking forward to collaborating with all of you!",
    country: "South Korea",
    city: "Seoul",
    phone: "(222) 333-4444",
    socialMedia: [
      { name: "GitHub", link: "https://github.com/robertkim/" },
      { name: "Twitter", link: "https://twitter.com/robertkim/" },
    ],
    activities: ["Playing piano", "Gaming", "Hiking", "Frontend development"],
    status: "Coding is my passion! 💻",
  },
  {
    name: "Alexei Petrov",
    img: "https://sun9-61.userapi.com/impg/UgzIg6XPG2MuiA2YWB5l6g-luAam8CD0THkwQA/8AczZot5ybM.jpg?size=900x900&quality=96&sign=6d7fd414676450be972ce328c07e0fe0&c_uniq_tag=wJLM1Ds8cqBeG5P6wBsOb8wjTUo3P1fip-_wGxowm74&type=album",
    message: "Привет! Excited to work on challenging projects!",
    country: "Russia",
    city: "St. Petersburg",
    phone: "(111) 222-3333",
    socialMedia: [
      { name: "GitHub", link: "https://github.com/alexeipetrov/" },
      { name: "LinkedIn", link: "https://www.linkedin.com/in/alexeipetrov/" },
    ],
    activities: ["Swimming", "Reading", "Soccer", "Mobile development"],
    status: "Stay positive and keep coding! 👨‍💻",
  },
  {
    name: "Liam Johnson",
    img: "https://static.tildacdn.com/tild6137-3639-4339-b966-663732353962/photo.png",
    message: "Hello everyone! Let's build something amazing together!",
    country: "United Kingdom",
    city: "London",
    phone: "(777) 888-9999",
    socialMedia: [
      { name: "Instagram", link: "https://www.instagram.com/liamjohnson/" },
      { name: "Twitter", link: "https://twitter.com/liamjohnson/" },
    ],
    activities: ["Playing guitar", "Traveling", "Skiing", "UI/UX design"],
    status: "Coding is my superpower! 💪",
  },
  {
    name: "Maximilian Schmidt",
    img: "https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_auto,w_1400/fl_lossy,pg_1/ankj5upoh8uiolkihlsv/memoji-3?fimg-client-default",
    message: "Greetings! Looking forward to collaborating with you all!",
    country: "Germany",
    city: "Berlin",
    phone: "(444) 555-6666",
    socialMedia: [
      { name: "GitHub", link: "https://github.com/maximilianschmidt/" },
      {
        name: "LinkedIn",
        link: "https://www.linkedin.com/in/maximilianschmidt/",
      },
    ],
    activities: [
      "Playing piano",
      "Reading",
      "Photography",
      "Backend development",
    ],
    status: "Coding is life! 🚀",
  },
  {
    name: "Nathan Brown",
    img: "https://yt3.ggpht.com/ytc/AKedOLQY7OsJDRrfAKm0MgXsgkRgYGVwdt-qHr1PwfNQlg=s900-c-k-c0x00ffffff-no-rj",
    message: "Hey everyone! Let's create something awesome!",
    country: "United States",
    city: "Los Angeles",
    phone: "(888) 999-0000",
    socialMedia: [
      { name: "Instagram", link: "https://www.instagram.com/nathanbrown/" },
      { name: "Twitter", link: "https://twitter.com/nathanbrown/" },
    ],
    activities: ["Drawing", "Basketball", "Cooking", "Full-stack development"],
    status: "Enjoying the journey of coding! 🎯",
  },
  {
    name: "Oliver Kowalski",
    img: "https://cdn141.picsart.com/310347862009211.png",
    message: "Greetings, excited to be part of this team!",
    country: "Poland",
    city: "Warsaw",
    phone: "(999) 000-1111",
    socialMedia: [
      { name: "GitHub", link: "https://github.com/oliverkowalski/" },
      { name: "LinkedIn", link: "https://www.linkedin.com/in/oliverkowalski/" },
    ],
    activities: ["Reading", "Playing guitar", "Traveling", "Data science"],
    status: "Coding my way to success! 🌟",
  },
  {
    name: "Daniel Lee",
    img: "https://cdn.klook.com/upload/img200X200/5e7e848e51c948b95833df0215cfb91e.jpg",
    message: "Hello, let's build something innovative!",
    country: "South Korea",
    city: "Seoul",
    phone: "(555) 444-3333",
    socialMedia: [
      { name: "Twitter", link: "https://twitter.com/daniellee/" },
      { name: "LinkedIn", link: "https://www.linkedin.com/in/daniellee/" },
    ],
    activities: ["Reading", "Soccer", "Hiking", "Machine learning"],
    status: "Coding my dreams into reality! ✨",
  },
];
export const themes = [
  {
    background: "#1A1A2E",
    color: "#FFFFFF",
    primaryColor: "#0F3460",
  },
  {
    background: "#461220",
    color: "#FFFFFF",
    primaryColor: "#E94560",
  },
  {
    background: "#192A51",
    color: "#FFFFFF",
    primaryColor: "#967AA1",
  },
  {
    background: "#F7B267",
    color: "#000000",
    primaryColor: "#F4845F",
  },
  {
    background: "#F25F5C",
    color: "#000000",
    primaryColor: "#642B36",
  },
  {
    background: "#231F20",
    color: "#FFF",
    primaryColor: "#BB4430",
  },
];
